name: Python CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          pip install poetry
          make install
      - name: Install package
        run: |
          make build
          make package-install
      - name: Run linter
        run: |
          pip install flake8
          make lint
        continue-on-error: true
      - name: Run pytest
        run: |
          pip install pytest
          pip install pytest-cov
          make test
      - name: Test & publish code coverage
        uses: paambaati/codeclimate-action@v3.2.0
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
        with:
          coverageCommand: make test-coverage
          debug: true
